#!/bin/bash

FILE_COMPILE="$HOME/Documents/Project/blog_website_fiber/cmd/server"
TARGET_COMPILE="$HOME/Documents/Project/blog_website_fiber/cmd/main.go"

go build \
             -trimpath \
             -ldflags="-w -s" \
             -gcflags="-B -C -l -N" \
             -tags=netgo \
             -installsuffix=netgo \
             -o $FILE_COMPILE \
             -a \
             $TARGET_COMPILE

$FILE_COMPILE
